README.md
Atualizo assim que tivermos mais definições. Já realizamos a 1ª Edição Online e a 2ª em Lisboa, já está definido a 3ª em SP 2023.
=> + Gambiconf

README.md
=> insere cpbr e elas por elas

README.md
Adicionei um lista que estou construindo e que fazem sentido para nós na Vindi atualmente
=> Eventos importantes para o Roberson

README.md
- Lista em ordem alfabética
- Adicionado evento Front in Floripa
- Ajuste em erros ortográficos
=> chore: adicionado novo evento e lista ordenada em ordem alfabetica

README.md
Olá, gostaria de deixar minha contribuição.😆
=> CTO Summit - Evento online - Evento de liderança e gestão de TI

README.md
- Achei mais legal colocar numa visualização por tópicos, aquela de tabela acho sem graça.
- Também preferi colocar em ordem crescente ao invés de alfabética.
https://github.com/Abacatinhos/eventos-tech-brasil/issues/2
=> refact visualização de eventos

README.md
=> Update readme and add events

README.md
=> Add event patch

README.md
Workshops gratuitos de programação para mulheres (cis e trans)
=> Add Django Girls Parnaíba e Teresina <3

README.md
hi everyone, good day!! I am adding some devops events.
=> adding some devops events

README.md
A ser realizada em Belo Horizonte
=> Adição da Conferência de Segurança da Informação BHack 11ª edição

README.md
Inserção do evento EXPOTEC na lista dos eventos do mês de novembro.
=> Event-EXPOTEC

README.md
added new event in parnaiba-pi
=> added new event

README.md
O evento ainda não tem página oficial.
Linkei a live de abertura
=> Imersão React - Alura

README.md
E retirado um asterisco que estava a mais no FrontIn. 
Adequando ao padrão do repositório.
=> Colocado o estado no evento Github Field day

README.md
Adiciona o evendo  Xp Educação Dev Summit V. (closes https://github.com/Abacatinhos/eventos-tech-brasil/issues/51)
=> Adiciona Xp Educação Dev Summit V

README.md
O SULCOMP é realizado bianualmente e conta com várias atividades como Palestras, Sessão Oral, Sessão Pôster e VIII Workshop de Trabalhos Acadêmicos. As apresentações poderão ser híbridas (presencial ou remota)
=> Adiciona o x sulcomp 2022

README.md
Acrescentei o evento Conferência CSS Brasil 2023 + Code In The Dark
=> Acrescentei o evento Conferência CSS Brasil 2023 + Code In The Dark

README.md
Adicionei o evento Innovators Hive do Google Cloud que acontecerá no dia 25 de Novembro.
=> Add Innovators Hive no Google Cloud Next

README.md
Adiciona o evento WeniXP. (closes #66 )
=> Adiciona evento WeniXP

README.md
=> adding more events

README.md
Add Caravana cloud and data in Curitiba and Salvador
=> add Caravana cloud and data

README.md
Incluindo evento Universo TOTVS 2023
=> Incluindo evento Universo TOTVS 2023

.github/ISSUE_TEMPLATE/issue.yml, .github/workflows/evento.yml, README.md
@pachicodes eu estou submetendo aqui para você analisar se é interessante para vocês...
Basicamente oque eu fiz aqui, foi uma automação usando GitHub Actions e as Issues, onde uma pessoa pode abrir uma issue com os dados do evento, e o mesmo será incluido automaticamente no Readme.md do repositório.
Se quiser uma explicação mais detalhada, me chama que te explico oque eu fiz.
=> incluindo automaçao

README.md
Acrescentando o III Congresso de Tecnologia da Informação do IFSul Passo Fundo
=> add https://congressoti.passofundo.ifsul.edu.br/

README.md
Adicionado evento Febraban tech, adicionado link para o evento e também adicionado a badge de evento híbrido a Campus Party Brasil
=> Adicionado evento Febraban tech

README.md
Evento do dia 24/07 do[ Frontend CE](https://frontendce.com.br/)
=> add eventos do dia 24/07

README.md
Adicionando o Front in Floripa =]
=> adicionando frontinfloripa

README.md
Adiciona evento Ecossistema Mobile 2023
=> adiciona ecossistema mobile

README.md
Adicionando Django Girls Parnaiba - Um workshop gratuito de programação para mulheres em Parnaiba-PI
=> Add Django Girls Parnaiba <3

README.md
Foram adicionados eventos que ocorrerão em Outubro de 2023.
=> Adicionando eventos em outubro 2023

README.md
- Modificação da data do evento _"Caravana Cloud and Data - Edição Recife"_ do dia **30/03/2024** para o dia **06/04/2024**, conforme data descrita no site do evento.
- Adição do evento _"Mulher Tech Sim Senhor - 9º Edição"_, que irá acontecer na Paraíba, no dia **02/03/2024** - close #137 
- Adição do evento "_2º Meetup PARAÍ (Comunidade Técnica de IA da Paraíba)_", que irá acontecer na Paraíba, no dia **20/02/2024** - close #138 
- Adição de evento "_Guia Anônima Conference_", que irá ser online, com data a ser anunciada, na seção de TBA.
=> Feature: Adicionando e Ajustando data de Eventos

README.md
Adicionando os eventos que ocorrerão em campinas:
- 01/03 - NodeBR 68 - IFood - Frontend Universe
- 25/05 - Frontin Campinas 2024
=> [Docs] Adding events of Campinas/SP

README.md
- Adição do evento _"Microsoft AI Tour"_, que irá acontecer em São Paulo, no dia **21/03/2024** - close #145 
- Adição do evento _"Recife Data Saturday - 2ª Edição"_, que irá acontecer em Pernambuco, no dia **16/03/2024** - close #144
=> Feature: Adição do Evento da Microsoft e de Data Security

README.md
- Adição do evento _"DEVPIRA .NET Wknd"_, que irá acontecer em São Paulo, no dia **02/03/2024** - close #149
=> Feature: Adição de Evento

README.md
Adicionando a [Campus Party Brasil 16 (CPBR16)](https://brasil.campus-party.org/cpbr16/) que acontecerá em SP.
=> adicionando campus party brasil 16 - SP

README.md
Adicionado 
PyCaxias em Caxias do sul
Python Brasil
Python Cerrado
=> Add python events

README.md
- Foram realizadas correções pontuais para padronizar conforme outros eventos. Correções tais como adição de "-" entre o nome do evento e local, além de ajustes em datas, adicionando espaçamento e deixando mais verboso eventos com mais de 2 dias.
=> Refactor: Correção de Padrões de Estilo

README.md
Adiciona o International Women's Day Cerrado 2024, presencial em Goiânia
=> Adicionar IWD Cerrado 2024

README.md
Adiciona a 15° edição da comunidade Thasfin
=> Add 15th edition of the Thasfin Community

README.md
- Adição do evento _"TechVerso Fadergs & GDG"_, que irá acontecer em Porto Alegre/RS, no dia **02/04/2024** - close #164
=> Feature: Adicionando Evento TechVerso Fadergs & GDG

README.md
- Adição do evento _"NullByte Security Conference"_, que irá acontecer em Salvador/BA, no dia **30/11/2024** - close #166
- Adição do evento _"Hacking na Web Day Salvador"_, que irá acontecer em Salvador/BA, no dia **04/05/2024** - close #167
=>  Feature: Adicionando Evento Hacking na Web Day e NullByte Security Conference

README.md
=> eventos adicionados

README.md
O site ainda está sendo atualizado, mas as isncrições já estão abertas.
=> Inclusão do evento ElixirDays

README.md
O site ainda não foi atualizado, mas a data já foi anunciada no Instagram: https://www.instagram.com/p/C4va_Sogxom/?hl=en
=> add front in sampa

README.md
Evento acadêmico mas aberto a todos e todas
=> XXVII Ibero-American Conference on Software Engineering (CIbSE 2024)

README.md
add:
- FLISoL
- Cloud Summit Cerrado
- DevOpsDays Juiz de Fora
- App Growth Summit
- Mind The Sec
- DevOpsDays Belo Horizonte 
- Futurecom
- UXConf BR 
- LatAm Cyber Summit & CS4CA LATAM (Cyber Security for Critical Assets)
- DCD>Connect
- Big Data Brazil Experience
=> add FLISoL

README.md
Adicionados eventos que constam no [calendário](https://www.sbc.org.br/eventos/calendario-de-eventos/ano/2024) da Sociedade Brasileira de Computação
=> Adicionados eventos da SBC

README.md
Issue: https://github.com/Abacatinhos/eventos-tech-brasil/issues/180
=> adding RogaDX and hacking na web RJ and SP

README.md
- **Data:** 09 de novembro de 2024
- [Codecon Select Experience](https://codecon.dev/select)
=> Adding event for November 2024 - codecon select experience

README.md
Adicionando GambiConf: https://gambiconf.dev/
=> adding GambiConf 2024

.github/scripts/validateReadme.js, .github/workflows/markdown-lint.yml, README.md
- Adição do Github Actions para validação do Markdown. Ele valida o padrão adotado, em cada um dos meses, e TBA. 
- Correção de valores dentro do README.md, para seguir o padrão.
=> Add Custom Markdown Lint

README.md
Adicionei a IA Conference em São Paulo dia 21 de Agosto.
=> Add IA Conference Sao Paulo

README.md
Adicionei o evento AIED no dia 8 de Julho 
A Cesar School vai sediar a 25° edição da AIED. O evento tem como objetivo ampliar o alcance de pesquisas inovadoras e de alta qualidade sobre sistemas assistidos por IA e abordagens de ciência cognitiva para aplicações educacionais computacionais
Parceiros: UFPE, UPE, UFRPE, UFAM e UFAL
=> Add International Conference on Artificial Intelligence in Education

README.md
- Adição do evento _"CodeHERs - Desvendando a Engenharia Reversa"_, que irá acontecer Online, nos dias **06/07/2024, 07/07/2024, 13/07/2024 e 14/07/2024** - close #198
=> Add CodeHERs Event

README.md
=> Add June Event

README.md
=> Atualização dia do evento PyCaxias

README.md
Novos eventos adicionados em:
JUNHO
- Kubernetes Birthday Brazil - 10 anos
- Cisco ACLs na prática
AGOSTO
- ConFLOSS 24 - Conferência De Free/Libre E Open Source Software
=> Adicionando novos eventos

README.md
Adicionando os seguintes meetups para o calendário:
**- Junho:**
Pyladies SP online;
Meetup GitTogether.
**- Julho:**
Automação RPA - BotCity.
=> Adiciona meetups - Junho e Julho

README.md
Evento presencial em Piracicaba SP sobre Agilidade
=> Adicionando Caipira Ágil 2024

README.md
**Confirmação do DevOpsDays Curitiba:**
- Evento presencial em [Prédio Dom Pedro I - UFPR (Universidade Federal do Paraná), Curitiba - PR](https://www.sympla.com.br/evento/devopsdays-curitiba-2024/2547544#event-location)
- Página para adquirir os ingressos gratuitamente: https://www.sympla.com.br/evento/devopsdays-curitiba-2024/2547544
**Local:**
Prédio Dom Pedro I - UFPR (Universidade Federal do Paraná)
Rua General Carneiro, 460, Anfi 100 e Sala Prof. Homero de Barros, Centro
Curitiba, PR
=> DevOps Days Curitiba

README.md
Recruta tech é um evento que vai acontecer dia 05 de outubro das 08h - 18h no sebrae Rua Caeté, 150 no prado velho - Curitiba - Pr
=> Adicionando evento de T.I RecrutaTech na lista

README.md
Adicionado evento DevConverge LATAM anuncionado no [LinkedIn](https://www.linkedin.com/company/java-dev-converge-latam/)
=> feat(readme): Add DevConverge LATAM event on september 25th

README.md
=> Latinoware 2024

README.md
Saiba mais em https://meetup.com/developerparana e https://devpr.org
=> Adiciona eventos do DevPR

README.md
**Confirme presença:** [Evento Meetup](https://www.meetup.com/pt-BR/soujava-brasilia/events/303105127/
)
**Local:** BRBLAB
**Endereço:** Residência Oficial da Granja do Torto - Parque Tecnológico de Brasília, Edifício de Governança Bloco A, Lote 4, Brasília - DF, 70635-815
=> Adiciona meetup SouJava Brasília + Esquenta TDC

README.md
_eng_
Added the link to Seniortec Experience 2024, that is going to happen September 25th
_pt-br_
Adicionado o link para a Seniortec Experience 2024, que acontecerá dia 25 de setembro.
=> add: event seniortec experience

README.md
:sparkles: Add DevOpsDays Brasília 2024
=> DevOpsDays Brasília

README.md
Adicionado evento em Belo Horizonte/MG. Evento organizado pelo grupo de profissionais conhecido como SQL BH.
=> Added - Data Saturday BH

README.md
- Inclui evento OWASP para 01/10
- Insere evento BHack 30/11 e 01/12
=> Adiciona eventos da OWASP e BHack ao calendário

README.md
Evento da comunidade Data Pipeline Code online para discutir sobre o impacto da engenharia de dados nos negócios
=> Add Webinar: Engenharia de Dados e Negócios

README.md
- Adição do evento SorocabaCSS que vai acontecer online na 26/10/2024
=> Adição do SorocabaCSS

README.md
Adicionei o evento que ocorrerá em Fortaleza, chamado Siará Tech Summit.
=> Siará Tech Summit, evento em Fortaleza/CE.

README.md
Adicionado meetup que acontecerá em São Paulo SP.
=> add BotCity meetup SP

README.md
- Adição do evento "Transformando o Futuro: Desenvolvimento e Inovação com Inteligência Artificial", que irá acontecer de forma presencial no dia 29/10/2024 - close #274
=> feat: add event Desenvolvimento e Inovação com Inteligência Artificial

README.md
Olá, adicionei um evento que irá ocorrer dia 31 de outubro de modo online.
=> Adicionado evento tecnologia dia 31

README.md
Olá, tudo bem?  Espero que sim! :)
Estou adicionando o evento da [21° Semana Nacional de Ciência e Tecnologia (SNCT)](https://www.snctma2024.com/) que acontece em São Luís/MA agora em Outubro. 
Desde já agradeço a colaboração!
=> Adiciona o evento da 21° Semana Nacional de Ciência e Tecnologia

README.md
Adicionei 3 eventos:
19/10/24 - golang day
30/10/24 - meetup craftsman ship
31/10/24 - Meetup 9 Nubank Engineering - Plataforma em foco: Mobile e observabilidade estratégica
=> Adicionei Golang day, craftmans ship e nubank meetup9

README.md
Adicionei 17th Brazilian Symposium on Bioinformatics BSB 2024 e 27th Brazilian Symposium on Formal Methods, que acontecem em Dezembro em Vitória, ambos organizados pela SBC.
=> Adiciona BSB 2024 e SBMF 2024

README.md
7ª edição do maior evento gratuito e online para pessoas que criam, desenvolvem e lideram Produtos Digitais no Brasil, nos dias 28, 29 e 30 de outubro.
=> Digital Product Week 2024

README.md
Adicionei evento FrontIn Floripa que acontece dia 16 de novembro em Florianópolis.
=> add evento front in floripa

README.md
Fiquei em dúvida se o título do mês fica antes ou depois da tag ``
=> Incluindo IAM Tech Day SP 2025-04-10e11

README.md
- Correção de estilos que não passavam nos testes, colocando-os dentro do padrão do repositório
- Modificação nas divisórias dos meses
- Adição de link do evento **Nubank DS & ML Meetup**.
_PS:. A modificação de divisória dos meses é para melhorar o lint, e preparar o caminho para a feature de criação de PR através de issues_
=> fix(style): change events style and 'tags' for ci

README.md
Evento BBDW - Banco do Brasil Digital Week
Evento gratuito que acontece em Brasilia.
=> Add: BBDW Brasilia

README.md
Resolve issues #315 e #305 e adiciona evento DevFest Santos 2024
=> Resolve Issues + Add DevFest Santos 2024

README.md
A 1a Conferência Latino-Americana de Ética em Inteligência Artificial (IA) - 1st Latin American Ethics on Artificial Intelligence (LAAI-Ethics) será realizada em Niterói, Brasil, de 27 a 29 de novembro de 2024, no Instituto de Computação - Universidade Federal Fluminense UFF), Campus Praia Vermelha.
=> Feat | Adicionando evento de IA Niterói/RJ

README.md
- Adição do evento "DevOpsDays Natal", que irá acontecer de forma presencial no dia 23/11/2024 - close #319
=> Adição do Evento DevOpsDays Natal

README.md
Adicionar na lista o evento PHPeste 2024.
=> doc: Adicionar evento PHPeste 2024 🐘

README.md
Correção de URL para passar no lint
=> Correção de formatação de url no markdown

README.md
Post: [Linkedin](https://www.linkedin.com/events/7265711951761076225/)
Confirme presença: [Evento Meetup](https://bit.ly/03-12-24)
Local: Cooperforte
Endereço: Edifício Parque Cidade Corporate - Torre C, 9º andar
=> Adiciona meetup SouJava Brasília 03 de dezembro

src/db/database.json
- Adicionar novos eventos no Database, para que seja incluído na geração automatica do README.md
=> feat: add new events to database

.github/workflows/create-event.yml, .github/workflows/delete-event.yml
- Correção de nome de Branch principal, de master para main. Por não existir a branch master, não é possível abrir um Pull Request, já que ela não existe.
=> Fix(CI): Correção de Nome de Branch Principal

.github/workflows/create-event.yml, .github/workflows/delete-event.yml, README.md, src/db/database.json
Reverts Abacatinhos/agenda-tech-brasil#360
=> Revert "Agenda/Evento: Hacking na Web Day - Florianópolis"

README.md, src/db/database.json
Resolve issue 599, solicitada por @fabiobrasileiroo , sobre VII Meetup PyData em Manaus, que estava como online, mas é presencial
=> 599 - corrigir evento PyData Manaus

src/templates/events.md.j2
=> Adicionar informações da versão web

src/templates/events.md.j2
- Modificar Titulo no README para Agenda Tech, ao invés de Eventos Tech
=> Modificar Titulo no README

README.md, src/db/database.json
=> Agenda/Evento: 1º Encontro de Mulheres em Tecnologia no Cerrado

.github/ISSUE_TEMPLATE/05 - archive-event.yml, .github/workflows/archive-events.yml, .github/workflows/change_issue_title.yml, src/archive.py
- Esse PR tem como objetivo incluir a opção de issue para arquivar meses e/ou anos que já passaram, deixando o readme.md mais "limpo".
=> Feature: Automação para Arquivar Meses e/ou Anos

src/db/database.json
- O objetivo desse PR é adicionar os eventos de 2022, como uma forma de preparar para a geração de markdown para meses e anos antigos. Hoje, esse processo é feito de forma manual. O objetivo final é tornar esse processo automatizado, através da issue de arquivamento de meses e anos.
=> Adicionar Eventos de 2022 no Arquivo de Database

src/db/database.json
- O objetivo desse PR é adicionar os eventos de 2023, como uma forma de preparar para a geração de markdown para meses e anos antigos. Hoje, esse processo é feito de forma manual. O objetivo final é tornar esse processo automatizado, através da issue de arquivamento de meses e anos.
=> Adicionar Eventos de 2023 no Arquivo de Database

src/db/database.json
- Esse PR corrige o problema de Databse que trava a pipeline de criação de novos PRs de forma automática
=> Correção do Database

.github/workflows/archive-events.yml, .github/workflows/create-event.yml, .github/workflows/delete-event.yml, .github/workflows/generate-markdown.yml
Adiciona a Feature de criação do Markdown após qualquer push na main branch.
No path '.github/workflows/generate-markdown.yml' você pode encontrar o workflow criado, mas os arquivos para Criar, Arquivar e Deletar eventos também sofreram atualizações.
Ao fazer um fork do repositório, é possível testar com um push na `main` que altere o `database.json` ou não. De qualquer forma, é esperado que o workflow rode sem erros, adicionando um commit quando houver alteração no arquivo `database.json`.
- Optei por manter o nome 'markdown' ao invés de 'README', uma vez que o objetivo principal é a  geração automática de um arquivo markdown. Dessa forma, a abordagem pode ser reaproveitada de forma mais simples, sem amarrar a lógica a um único arquivo.
- Também optei por criar um novo workflow ao invés …
=> Feature/Geração de Markdown após Push

src/db/database.json
- Esse PR tem como objetivo corrigir a estrutura do database.json, que hoje está incorreto.
=> Hotfix: Corrigir Database

README.md, src/db/database.json
O objetivo dessa PR é realizar alguns ajustes no database, para que as Actions de geração de Markdown continuem sendo realizados sem problemas.
- Remover evento phpeste do README e adicionar corretamente no database
- Adicionar tipo de evento presencial no evento promovido pela cbsoft
- Remover evento Semana IBM do README
- Corrigir inconsistências no database que geravam erro de parsing. Resolve #1182 (Reportado por: Gustavo Martins @GusMartins499)
=> Adicionar Informações Faltantes que Geram Erro no Database

README.md
Adicionando mais um dia da [GambiConf](https://gambiconf.dev/)
=> Update GambiConf data

README.md
=> adiciona mvp conf como evento

README.md
=> Adiciona evento PySul
